sudo: false
env:
- PATH=$PATH:$HOME/go_appengine/
before_install:
- openssl aes-256-cbc -K $encrypted_7c38666f388e_key -iv $encrypted_7c38666f388e_iv
  -in frederic-30442d4ec629.json.enc -out frederic-30442d4ec629.json
  -d
- wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.30.zip
  --directory-prefix=$HOME/
- pwd
- unzip $HOME/go_appengine_sdk_linux_amd64-1.9.30.zip -d $HOME
script:
- goapp test
deploy:
  provider: gae
  keyfile: frederic-30442d4ec629.json
  default: true
  project: frederic-svdp
