sudo:	false
env:
- PATH=$PATH:$HOME/go_appengine/
before_install:
- wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.30.zip
- unzip go_appengine_sdk_linux_amd64-1.9.30.zip
script:
- echo $PATH
- ls $HOME/go_appengine/
- goapp test
