sudo:	false
env:
- PATH=$PATH:$HOME/go_appengine/
before_install:
- wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.64.zip --directory-prefix=$HOME/
- pwd 
- unzip $HOME/go_appengine_sdk_linux_amd64-1.9.64.zip -d $HOME
- go get golang.org/x/net/context
- go get -u google.golang.org/appengine/...
script:
- goapp test
