application: frederic-svdp
version: 3
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js
  secure: always
- url: /images
  static_dir: images
  secure: always
- url: /.*
  script: _go_app
  login: required
  secure: always

